# Generated by Django 4.2.6 on 2024-05-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='semester',
            field=models.CharField(choices=[('İlkbahar', 'İlkbahar'), ('Sonbahar', 'Sonbahar')], max_length=8),
        ),
    ]
