# Generated by Django 4.2.6 on 2024-05-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classes_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
    ]
