# Generated by Django 4.2.6 on 2024-05-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_hall_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
