# Generated by Django 4.2.6 on 2024-05-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_alter_hall_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='slug',
        ),
    ]
