# Generated by Django 4.2.6 on 2024-05-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_remove_hall_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
