# Generated by Django 4.2.6 on 2024-03-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='login',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='school_number',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='surname',
        ),
    ]
