# Generated by Django 4.2.6 on 2024-03-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='papername',
        ),
    ]
