# Generated by Django 4.2.6 on 2024-03-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulings', '0002_remove_scheduling_papername'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='school_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
