# Generated by Django 4.2.6 on 2024-04-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
        ('schedulings', '0007_alter_scheduling_hallid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='hallid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.hall'),
        ),
    ]
