# Generated by Django 4.2.6 on 2024-05-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulings', '0009_scheduling_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='slug',
        ),
    ]
